config/routes.rb
Rails.application.routes.draw do
  resources :news
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name, :nickname])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :last_name, :nickname])
      end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :sub_title, :content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      @news = News.all
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/_header.html.erb
<header>
        <nav >
            <ul class="nav justify-content-end">
                <li class="nav-item"><%= link_to 'News', news_index_path ,class: 'nav-link'%></li>
                <% unless user_signed_in? %>
                  <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: 'nav-link'%></li>
                  <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path,class: 'nav-link'%></li>
                <% else%>
                <li class="nav-item"><%= link_to 'Logout', destroy_user_session_path,method: :delete, class: 'nav-link'%></li>
                <li class="nav-item"><%= link_to 'Edit', edit_user_registration_path ,class: 'nav-link' %></li>
                <%end%>

            </ul>
          </nav>
    </header>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dokidoki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">

        <%= yield %>

    </div>
  </body>
</html>
 

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :sub_tile %>
    <%= form.text_field :sub_tile %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Sub tile</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.sub_tile %></td>
        <td><%= news.content %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<div class="container">
        <h1>Nueva Noticia</h1>

        <%= render 'form', news: @news %>
        
        <%= link_to 'Back', news_index_path %>
</div>

app/views/news/show.html.erb
<div class="container text-center ">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Title:</strong>
      <%= @news.title %>
    </p>

    <p>
      <strong>Sub tile:</strong>
      <%= @news.sub_tile %>
    </p>

    <p>
      <strong>Content:</strong>
      <%= @news.content %>
    </p>

    <%= link_to 'Edit', edit_news_path(@news) %> |
    <%= link_to 'Back', news_index_path %>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    <h1>Bienvenido <%= current_user.name%> <%=current_user.last_name%></h1>
<% end%>
<% @news.each do |single|%>
<div class="card">
     <div class="">
        <h1 class="text-uppercase"><%=single.title%></h1>
        <p><%=single.sub_title%></p>
    </div>
    <div>
        <p><%=single.content%></p>
    </div>
</div>

    
<%end%>